- name: Add PostgreSQL repository
  command: "yum -y install https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm"

- name: Install PostgreSQL
  yum: name=postgresql{{ pg_version }}-server

- name: InitDB
  command: "/usr/pgsql-12/bin/postgresql-12-setup initdb"

- name: Start service
  command: "systemctl start postgresql-12"

- name: Enable service
  command: "systemctl enable postgresql-12"

- name: Create DB user
  command: "psql postgres && CREATE ROLE admin LOGIN PASSWORD 'admin';"

- name: Create DB
  command: "psql postgres && CREATE DATABASE python WITH OWNER = admin"