#- name: Add PostgreSQL repository
#  yum-repository:
#    name: postgresql{{ pg_version }}-server
#    description: posrgresql{{ pg_version}}
#    baseurl: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
#    enabled: "yes"
#    gpgcheck: "no"
#    validate_certs: "no"
- name: Add PostgreSQL repo
  command: "sudo yum install -y https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm"
  register: result
  failed_when: "'Nothing to do' in result.stdout and result.rc != 0"
  args:
    warn: false
  #ignore_errors: true

- name: Install PostgreSQL
  yum: 
    name: postgresql{{ pg_version }}-server
    state: latest
  become: true

- name: InitDB
  command: "/usr/pgsql-12/bin/postgresql-12-setup initdb"
  become: true

- name: Start service
  command: "systemctl start postgresql-12"
  become: true

- name: Enable service
  command: "systemctl enable postgresql-12"
  become: true