#- name: Add PostgreSQL repository
#  yum-repository:
#    name: postgresql{{ pg_version }}-server
#    description: posrgresql{{ pg_version}}
#    baseurl: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
#    enabled: "yes"
#    gpgcheck: "no"
#    validate_certs: "no"
- name: install python
  become: true
  raw: yum -y install python
  register: result
  failed_when: 
  - not result.stderr is search('Nothing to do')
  - result.rc != 0

- name: Add PostgreSQL repo
  become: true
  command: "yum install -y https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm"
  register: result
  failed_when: 
  - not result.stderr is search('Nothing to do')
  - result.rc != 0
  #ignore_errors: true

- name: Install PostgreSQL
  yum: 
    name: postgresql{{ pg_version }}-server
    state: latest
  become: true

- name: InitDB
  command: "/usr/pgsql-12/bin/postgresql-12-setup initdb"
  register: result_init
  failed_when: "'Data directory is not empty' not in result_init.stdout and result_init.rc != 0"
  become: true

- name: Start service
  command: "systemctl start postgresql-12"
  become: true

- name: Enable service
  command: "systemctl enable postgresql-12"
  become: true