#- name: Create DB user
#  command: "psql postgres && CREATE USER admin WITH PASSWORD 'admin';"
#  become: true
#  become_user: postgres

#- name: Create DB
#  command: "psql postgres && CREATE DATABASE python WITH OWNER = admin"
#  become: true
#  become_user: postgres

- name: Create_DB
  become: true
  become_user: postgres
  postgresql_db: name={{ db_name }}
    template='template0'
    state=present

- name: create_user
  become: true
  become_user: postgres
  postgresql_user: db= {{ db_name }}
    name={{ db_user }}
    password={{ db_password }}
    priv=ALL
    state=present

- name: deny permissions
  become: true
  become_user: postgres
  postgresql_user: name {{ db_user }}
    role_attr_flags=NOSUPERUSER,NOCREATEDB
    state=present